name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    name: 🔧 Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8

    - name: Code Quality Check (Flake8)
      run: flake8 smart_factory_system/

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD/smart_factory_system" >> $GITHUB_ENV

    - name: Run Unit Tests
      run: pytest smart_factory_system/tests

    - name: Test Coverage Report
      run: pytest --cov=smart_factory_system --cov-report=term-missing
