name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
          - development
          - testing
      version:
        description: 'Version of the application to deploy'
        default: '1.0.0'
        type: string
      notify_email:
        description: 'Email address to send notification to'
        required: false
        default: 'rabbittrix@hotmail.com'
        type: string
      notify_slack:
        description: 'Slack channel to send notification to'
        required: false
        default: 'Roberto de Souza'
        type: string

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          echo "Running tests for ${{ github.event.inputs.environment || 'CI trigger' }}..."
          pytest --cov=. --cov-report=term-missing
          echo "Tests completed."

  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    needs: build-and-test
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Simulate deployment
        run: |
          echo "Deploying version ${{ github.event.inputs.version }} to environment: ${{ github.event.inputs.environment }}"
          echo "Notification email: ${{ github.event.inputs.notify_email }}"
          echo "Slack notification: ${{ github.event.inputs.notify_slack }}"
