name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies explicitly
        run: |
          python -m pip install --upgrade pip
          pip install pyvis==0.3.2 networkx==3.2.1

      - name: Install remaining dependencies
        run: |
          pip install -r requirements.txt

      - name: List directory contents (diagnostic)
        run: |
          echo "Listing the files in the current directory:"
          ls -R  # Lista recursivamente o conteúdo do diretório

      - name: Move pytest.ini to root
        run: mv pytest.ini smart_factory_system/pytest.ini

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/smart_factory_system" >> $GITHUB_ENV

      - name: Run tests
        working-directory: smart_factory_system
        run: pytest --cov=. --cov-report=term-missing

      - name: Lint code with flake8
        run: flake8 .